sudo: required
services:
    - docker

before_install:
    - docker build -t vivekkushwaha46/docker-react -f Dockerfile.dev .

scripts:
    - docker run vivekkushwaha46/docker-react npm run test -- --coverage